"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.routerUser = void 0;
const express_1 = require("express");
const user_controller_1 = require("../controllers/user-controller");
// import { uploads } from '../middlewares/multer-middleware';
const auth_middleware_1 = require("../middlewares/auth-middleware");
const multer_middleware_1 = require("../middlewares/multer-middleware");
exports.routerUser = (0, express_1.Router)();
exports.routerUser.post('/addmember', auth_middleware_1.authUser, multer_middleware_1.uploadProfilePicture.none(), user_controller_1.addMember);
exports.routerUser.post('/loginMember', multer_middleware_1.uploadProfilePicture.none(), user_controller_1.loginMember);
exports.routerUser.get('/getMember/:id', user_controller_1.getMember);
exports.routerUser.get('/getAllMember', auth_middleware_1.authUser, user_controller_1.getAllMember);
exports.routerUser.patch('/editMember/:id', auth_middleware_1.authUser, multer_middleware_1.uploadProfilePicture.single('image'), user_controller_1.editMember);
exports.routerUser.post('/visit/:id', user_controller_1.recordVisit);
exports.routerUser.get('/getTodayVisit', auth_middleware_1.authUser, user_controller_1.getTodayVisit);
exports.routerUser.get('/getVisitLog', auth_middleware_1.authUser, user_controller_1.getLogVisit);
exports.routerUser.get('/getpayment', auth_middleware_1.authUser, user_controller_1.getAllPayment);
exports.routerUser.post('/extendMember', multer_middleware_1.uploadProfilePicture.none(), user_controller_1.extendMember);
exports.routerUser.get('/getnotif', user_controller_1.getAllNotifications);
exports.routerUser.delete('/deleteMember', user_controller_1.deleteMember);
